---
title: "Secondary School Courses Ranked by Enrolment (2013-2014)"
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(readxl)
library(plotly)
```

```{r 1314-plot, fig.height=6}
clean_1314 <- read_rds("clean_1314.rds") %>% 
  group_by(Grade) %>% 
  arrange(desc(Enrolment)) %>% 
  slice(1:20)

plot_1314 <- clean_1314 %>% 
  ggplot(aes(x = fct_reorder(as.factor(`Course Code`), desc(Enrolment)),
             y = Enrolment,
             fill = `Pathway or Destination`,
             text = paste("Course Code:", `Course Code`, "\n",
                          "Course Description:", `Course Description`, "\n",
                          "# of Students Enrolled:", Enrolment, "\n",
                          "Pathway/Destination:", `Pathway or Destination`))) +
  geom_col() +
  facet_wrap(~ Grade, scales = "free") +
  scale_y_continuous(labels = scales::comma_format()) +
  scale_x_discrete(labels = NULL, breaks = "", name = "") +
  ylim(0, 180000) +
  labs(title = "Top 20 Secondary School Courses by Number of Students Enrolled (2013-2014)")

plot_1314 %>% 
  ggplotly(tooltip = "text") %>% 
  layout(width = 1000,
         height = 600,
         title = list(y = 0.97,
                      yanchor = "bottom"),
         legend = list(bgcolor = "#FFFFF0",
                       orientation = "v",
                       yanchor = "top",
                       y = 1))
```

